version: 2
updates:
  - package-ecosystem: npm
    directory: /hub_demo_frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: maven
    directory: /hub_demo_backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
