export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        outline: '#b9a79c',
        primary: '#fff8ef',
        'surface-dim': '#0b0909',
        'error-container': '#93000a',
        error: '#ff7a87',
        'on-primary': '#190607',
        'primary-fixed-dim': '#ff6b57',
        'tertiary-fixed-dim': '#31d5e6',
        'on-surface': '#fff8ef',
        'surface-container-highest': '#1a1514',
        'surface-container-lowest': '#070506',
        'on-tertiary-fixed': '#031214',
        tertiary: '#ffffff',
        'on-error': '#690005',
        'inverse-surface': '#fff8ef',
        'on-primary-fixed': '#190607',
        'surface-tint': '#ff4054',
        background: '#070506',
        'tertiary-container': '#31d5e6',
        'on-secondary-container': '#fff3d5',
        'secondary-fixed': '#ffc15d',
        'on-secondary-fixed-variant': '#4c2200',
        'on-tertiary': '#031214',
        secondary: '#ffc15d',
        'inverse-primary': '#b51227',
        'primary-fixed': '#ff4054',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#2b1600',
        'on-primary-fixed-variant': '#5c0c12',
        'secondary-container': '#ffc15d',
        'surface-container-low': '#0c090a',
        surface: '#12100f',
        'surface-variant': '#3d302e',
        'inverse-on-surface': '#1a1514',
        'on-primary-container': '#fff8ef',
        'surface-bright': '#241b19',
        'tertiary-fixed': '#31d5e6',
        'on-tertiary-fixed-variant': '#073f44',
        'outline-variant': '#65433f',
        'on-background': '#fff8ef',
        'on-secondary': '#2b1600',
        'on-surface-variant': '#e8d8c8',
        'primary-container': '#ff4054',
        'surface-container': '#12100f',
        'secondary-fixed-dim': '#d99537',
        'on-tertiary-container': '#e5fdff',
        'surface-container-high': '#171211'
      },
      fontFamily: {
        'display-lg': ['Anybody'],
        'label-mono': ['JetBrains Mono'],
        'body-md': ['Hanken Grotesk'],
        'headline-xl': ['Anybody'],
        'headline-lg': ['Anybody'],
        'body-lg': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Anybody'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
        'label-mono': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '800' }],
      },
      spacing: {
        'margin-mobile': '20px',
        'angle-offset': '12px',
        gutter: '24px',
        'margin-desktop': '64px',
        base: '8px',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
}
